const GAMES={"1":"Magic: The Gathering","2":"Yu-Gi-Oh!","3":"Pokémon","63":"Digimon Card Game","68":"One Piece Card Game","71":"Disney Lorcana"};
const DEFAULTS={fx:3.75,fees:12,margin:25,risk:6,fixed:2,idealPct:90,cond:{NM:100,LP:85,MP:70,HP:55,DMG:35}};
const state={status:null,current:null,currentCat:null,lot:[],photo:null,settings:Object.assign({},DEFAULTS)};
const $=id=>document.getElementById(id);
function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function norm(v){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/&/g," and ").replace(/[^a-z0-9]+/g," ").trim().replace(/\s+/g," ");}
function compact(v){return norm(v).replace(/\s+/g,"");}
function prefix2(v){v=compact(v);return v.length>=2?v.slice(0,2):(v+"_").slice(0,2);}
function usd(v){return "$"+Number(v||0).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2});}
function pen(v){return "S/ "+Number(v||0).toLocaleString("es-PE",{minimumFractionDigits:2,maximumFractionDigits:2});}
function toast(t){const e=$("toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200);}
function loadLocal(){try{const s=JSON.parse(localStorage.getItem("tcgScoutSettings")||"null");if(s)state.settings=Object.assign({},DEFAULTS,s,{cond:DEFAULTS.cond});const l=JSON.parse(localStorage.getItem("tcgScoutLot")||"[]");if(Array.isArray(l))state.lot=l;}catch(e){}syncSettings();renderLot();}
function persist(){localStorage.setItem("tcgScoutSettings",JSON.stringify(state.settings));localStorage.setItem("tcgScoutLot",JSON.stringify(state.lot));}
function syncSettings(){$("fxInput").value=state.settings.fx;$("feesInput").value=state.settings.fees;$("marginInput").value=state.settings.margin;$("riskInput").value=state.settings.risk;$("fixedInput").value=state.settings.fixed;$("idealPctInput").value=state.settings.idealPct;}
function saveSettings(){state.settings.fx=Number($("fxInput").value)||3.75;state.settings.fees=Number($("feesInput").value)||0;state.settings.margin=Number($("marginInput").value)||0;state.settings.risk=Number($("riskInput").value)||0;state.settings.fixed=Number($("fixedInput").value)||0;state.settings.idealPct=Number($("idealPctInput").value)||90;persist();$("settingsModal").classList.remove("open");renderCurrent();toast("Configuración guardada");}
function switchSection(id){document.querySelectorAll(".section").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll(".navBtn").forEach(x=>x.classList.toggle("active",x.dataset.target===id));window.scrollTo({top:0,behavior:"smooth"});}
function gameOptions(){const sel=$("gameSelect"),current=sel.value||"all";sel.innerHTML='<option value="all">Todos los juegos disponibles</option>';const available=state.status&&state.status.games?state.status.games:{};Object.keys(GAMES).forEach(id=>{const g=available[id],o=document.createElement("option");o.value=id;o.textContent=GAMES[id]+(g&&g.products===0?" — sin datos":"");o.disabled=!!(g&&g.products===0);sel.appendChild(o);});sel.value=[...sel.options].some(o=>o.value===current&&!o.disabled)?current:"all";}
async function loadStatus(showToast){const box=$("sourceStatus"),diag=$("diagnostics");try{const r=await fetch("data/status.json?v="+Date.now(),{cache:"no-store"});if(!r.ok)throw new Error("HTTP "+r.status);const s=await r.json();state.status=s;const d=new Date(s.builtAt);box.className="status ok";box.innerHTML="<b>TCGplayer activo</b> · snapshot "+d.toLocaleString("es-PE");let lines=["<b>Construido:</b> "+d.toLocaleString("es-PE")];Object.keys(s.games||{}).forEach(id=>{const g=s.games[id];lines.push("<b>"+esc(g.name)+"</b>: "+Number(g.products||0).toLocaleString()+" productos · "+Number(g.pricedProducts||0).toLocaleString()+" con precio · "+Number(g.failedGroups||0)+" sets con fallo");});diag.innerHTML=lines.join("<br>");gameOptions();if(showToast)toast("Snapshot actualizado");}catch(e){box.className="status bad";box.innerHTML="<b>Datos TCGplayer no disponibles:</b> "+esc(e.message);diag.textContent="No se pudo cargar data/status.json. Revisa el workflow de GitHub Pages.";gameOptions();}}
async function fetchShard(cat,type,key){const url="data/tcgplayer/"+cat+"/"+type+"/"+key+".json";const r=await fetch(url,{cache:"force-cache"});if(r.status===404)return[];if(!r.ok)throw new Error("HTTP "+r.status+" en "+url);return r.json();}
async function searchCards(){const q=$("queryInput").value.trim();if(q.length<2){toast("Escribe al menos 2 caracteres");return;}if(!state.status){toast("El snapshot aún no está disponible");return;}const info=$("searchInfo"),box=$("results");box.innerHTML='<div class="spin"></div>';info.textContent="Buscando en TCGplayer…";const selected=$("gameSelect").value;let cats=selected==="all"?Object.keys(state.status.games||{}).filter(id=>(state.status.games[id].products||0)>0):[selected];const nq=norm(q),cq=compact(q),tokens=nq.split(" ").filter(Boolean),keys=[...new Set(tokens.slice(0,4).map(prefix2))],codeKey=prefix2(cq),all=[],errors=[];for(const cat of cats){const jobs=keys.map(k=>fetchShard(cat,"name",k));jobs.push(fetchShard(cat,"code",codeKey));const settled=await Promise.allSettled(jobs);settled.forEach(s=>{if(s.status==="fulfilled")s.value.forEach(x=>all.push(Object.assign({_cat:cat},x)));else errors.push(String(s.reason));});}
const ded=new Map();all.forEach(x=>ded.set(x._cat+":"+x.i,x));let arr=[...ded.values()];arr.forEach(x=>{const hay=norm([x.n,x.s,x.a,x.c].join(" ")),code=compact(x.c);let score=0;if(code&&code===cq)score+=600;if(code&&code.includes(cq))score+=220;if(norm(x.n)===nq)score+=350;if(norm(x.n).startsWith(nq))score+=200;if(norm(x.n).includes(nq))score+=140;tokens.forEach(t=>{if(hay.includes(t))score+=35;});x._hay=hay;x._score=score;});arr=arr.filter(x=>tokens.every(t=>x._hay.includes(t))||(x.c&&compact(x.c).includes(cq))).sort((a,b)=>b._score-a._score||a.n.localeCompare(b.n)).slice(0,Number($("limitSelect").value)||20);renderResults(arr);info.textContent=arr.length?arr.length+" coincidencia(s) TCGplayer"+(errors.length?" · algunos shards fallaron":""):(errors.length?"No hubo resultados y parte del índice falló.":"Sin coincidencias.");}
function bestMarket(x){const vals=(x.p||[]).map(r=>Number(r[1]??r[3]??r[2])||0).filter(v=>v>0);return vals.length?Math.max(...vals):0;}
function renderResults(arr){const box=$("results");if(!arr.length){box.innerHTML='<div class="empty">No se encontraron cartas.</div>';return;}window._results=arr;box.innerHTML=arr.map((x,i)=>{const m=bestMarket(x);return '<div class="result" data-i="'+i+'"><img src="'+esc(x.m||"")+'" alt="" onerror="this.style.visibility=\'hidden\'"><div><h4>'+esc(x.n)+'</h4><div class="meta">'+esc(GAMES[x._cat]||"")+' · '+esc(x.s)+'<br>'+esc(x.c||"")+(x.r?' · '+esc(x.r):'')+'</div><span class="badge">TCGPLAYER</span></div><div class="priceMini">'+(m?usd(m):"—")+'<div class="meta">'+(x.p||[]).length+' variante(s)</div></div></div>';}).join("");box.querySelectorAll(".result").forEach(el=>el.addEventListener("click",()=>selectResult(Number(el.dataset.i))));}
function selectResult(i){const x=window._results&&window._results[i];if(!x)return;state.current=x;state.currentCat=x._cat;const s=$("variantSelect");if((x.p||[]).length)s.innerHTML=x.p.map((r,j)=>'<option value="'+j+'">'+esc(r[0]||"Normal")+' · Market '+(r[1]!=null?usd(r[1]):"—")+'</option>').join("");else s.innerHTML='<option value="-1">Sin precio actual</option>';$("detailCard").classList.remove("hidden");renderCurrent();$("detailCard").scrollIntoView({behavior:"smooth",block:"start"});}
function row(){const p=state.current?state.current.p||[]:[],i=Number($("variantSelect").value);return i>=0?p[i]:null;}
function valuation(base){const s=state.settings,c=$("conditionSelect").value,mult=(s.cond[c]||100)/100,market=base*s.fx*mult,fees=market*s.fees/100,risk=market*s.risk/100,goal=market*s.margin/100,max=Math.max(0,market-fees-risk-goal-s.fixed),ideal=max*s.idealPct/100,profit=Math.max(0,market-fees-s.fixed-ideal),roi=ideal?profit/ideal*100:0;return{market,max,ideal,profit,roi,mult};}
function historyKey(pid,sub){return"tcgHist_"+pid+"_"+String(sub).replace(/\W+/g,"_");}
function saveSnapshot(pid,sub,p){if(!p)return;let a=[];try{a=JSON.parse(localStorage.getItem(historyKey(pid,sub))||"[]");}catch(e){}const d=new Date().toISOString().slice(0,10);if(a.length&&a[a.length-1].d===d)a[a.length-1].p=p;else a.push({d,p});if(a.length>180)a=a.slice(-180);localStorage.setItem(historyKey(pid,sub),JSON.stringify(a));return a;}
function localTrend(a){if(!a||a.length<2)return a&&a.length?"1 punto":"sin datos";const latest=a[a.length-1].p;let base=a[0].p;const cutoff=Date.now()-30*86400000;for(const x of a){if(new Date(x.d+"T00:00:00Z").getTime()>=cutoff){base=x.p;break;}}const pct=base?((latest-base)/base*100):0;return(pct>0?"↑ +":pct<0?"↓ ":"→ ")+pct.toFixed(1)+"% / 30d local";}
function renderCurrent(){const x=state.current;if(!x)return;$("cardImage").src=x.m||"";$("cardName").textContent=x.n;$("cardGame").textContent=GAMES[state.currentCat]||"";$("cardSet").textContent=x.s||"";$("cardCode").textContent=[x.c,x.r].filter(Boolean).join(" · ");$("tcgplayerLink").href=x.u||("https://www.tcgplayer.com/product/"+x.i);const r=row();if(!r){["marketPen","pMarket","pLow","pMid","pHigh","pDirect","idealOffer","maxOffer","profit","roi"].forEach(id=>$(id).textContent="—");$("marketUsd").textContent="";$("priceBasis").textContent="TCGplayer no reporta precio para esta impresión.";$("trendLocal").textContent="—";return;}const sub=r[0],market=r[1],low=r[2],mid=r[3],high=r[4],direct=r[5],base=Number(market)||Number(mid)||Number(low)||0,basis=market!=null?"Market Price":(mid!=null?"Mid Price — Market no disponible":"Low Price — Market/Mid no disponibles"),v=valuation(base),hist=saveSnapshot(x.i,sub,base);$("marketPen").textContent=base?pen(v.market):"—";$("marketUsd").textContent=base?usd(base)+" USD · "+$("conditionSelect").value+" × "+(v.mult*100).toFixed(0)+"%":"";$("priceBasis").textContent=basis;$("pMarket").textContent=market!=null?usd(market):"—";$("pLow").textContent=low!=null?usd(low):"—";$("pMid").textContent=mid!=null?usd(mid):"—";$("pHigh").textContent=high!=null?usd(high):"—";$("pDirect").textContent=direct!=null?usd(direct):"—";$("trendLocal").textContent=localTrend(hist);$("idealOffer").textContent=base?pen(v.ideal):"—";$("maxOffer").textContent=base?pen(v.max):"—";$("profit").textContent=base?pen(v.profit):"—";$("roi").textContent=base?v.roi.toFixed(0)+"%":"—";}
function addLot(){const x=state.current,r=row();if(!x||!r)return;const base=Number(r[1])||Number(r[3])||Number(r[2])||0;if(!base){toast("La variante no tiene precio utilizable");return;}const v=valuation(base);state.lot.push({id:Date.now(),name:x.n,set:x.s,code:x.c,variant:r[0],condition:$("conditionSelect").value,market:v.market,offer:v.ideal});persist();renderLot();toast("Añadida al lote");}
function renderLot(){const b=$("lotList"),t=$("lotTotals");if(!state.lot.length){b.className="empty";b.textContent="No hay cartas añadidas.";t.classList.add("hidden");return;}b.className="";b.innerHTML=state.lot.map((x,i)=>'<div class="lotItem"><div><strong>'+esc(x.name)+' · '+esc(x.variant)+'</strong><small>'+esc(x.set)+' '+esc(x.code||"")+' · '+esc(x.condition)+'</small></div><div style="text-align:right"><strong>'+pen(x.offer)+'</strong><small>mercado '+pen(x.market)+' · <a href="#" data-rm="'+i+'" style="color:#ff8b9b">quitar</a></small></div></div>').join("");b.querySelectorAll("[data-rm]").forEach(a=>a.addEventListener("click",e=>{e.preventDefault();state.lot.splice(Number(a.dataset.rm),1);persist();renderLot();}));const m=state.lot.reduce((a,x)=>a+x.market,0),o=state.lot.reduce((a,x)=>a+x.offer,0);$("lotMarket").textContent=pen(m);$("lotOffer").textContent=pen(o);t.classList.remove("hidden");}
async function shareLot(){if(!state.lot.length){toast("El lote está vacío");return;}const m=state.lot.reduce((a,x)=>a+x.market,0),o=state.lot.reduce((a,x)=>a+x.offer,0),txt=["TCG STORE SCOUT — TCGPLAYER"].concat(state.lot.map((x,i)=>(i+1)+". "+x.name+" · "+x.variant+" · "+x.condition+" · Mercado "+pen(x.market)+" · Oferta "+pen(x.offer))).concat(["VALOR MERCADO: "+pen(m),"OFERTA IDEAL: "+pen(o)]).join("\n");try{if(navigator.share)await navigator.share({title:"TCG Store Scout",text:txt});else{await navigator.clipboard.writeText(txt);toast("Resumen copiado");}}catch(e){}}
function clearLot(){if(confirm("¿Vaciar el lote?")){state.lot=[];persist();renderLot();}}
function photoChanged(e){const f=e.target.files&&e.target.files[0];if(!f)return;state.photo=f;const rd=new FileReader();rd.onload=()=>{$("photoPreview").src=rd.result;$("photoPanel").classList.remove("hidden");};rd.readAsDataURL(f);}
function resetPhoto(){state.photo=null;$("cameraInput").value="";$("photoPanel").classList.add("hidden");$("ocrStatus").textContent="";}
async function ensureOCR(){if(window.Tesseract)return;await new Promise((resolve,reject)=>{const s=document.createElement("script");s.src="https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js";s.onload=resolve;s.onerror=()=>reject(new Error("No se pudo cargar el motor OCR"));document.head.appendChild(s);});}
async function runOCR(){if(!state.photo)return;const st=$("ocrStatus");try{st.textContent="Cargando OCR…";await ensureOCR();const out=await Tesseract.recognize(state.photo,"eng",{logger:m=>{if(m.status==="recognizing text")st.textContent="Leyendo carta… "+Math.round((m.progress||0)*100)+"%";}}),text=out.data.text||"",code=(text.match(/\b(?:BT|EX|ST|P|OP|EB|PRB)[ -]?\d{1,2}[ -]?\d{2,3}\b/i)||[])[0],lines=text.split(/\r?\n/).map(x=>x.trim()).filter(x=>x.length>=3&&x.length<=45&&!/^\d+$/.test(x)),q=code?code.replace(/\s+/g,""):lines[0]||"";if(!q)throw new Error("No pude extraer nombre o código; usa búsqueda manual.");$("queryInput").value=q;st.textContent="Detectado: "+q;await searchCards();}catch(e){st.textContent="OCR: "+e.message;}}
$("searchBtn").addEventListener("click",searchCards);$("queryInput").addEventListener("keydown",e=>{if(e.key==="Enter")searchCards();});$("variantSelect").addEventListener("change",renderCurrent);$("conditionSelect").addEventListener("change",renderCurrent);$("recalcBtn").addEventListener("click",renderCurrent);$("addLotBtn").addEventListener("click",addLot);$("cameraInput").addEventListener("change",photoChanged);$("changePhotoBtn").addEventListener("click",resetPhoto);$("ocrBtn").addEventListener("click",runOCR);$("clearLotBtn").addEventListener("click",clearLot);$("shareLotBtn").addEventListener("click",shareLot);$("refreshStatusBtn").addEventListener("click",()=>loadStatus(true));$("settingsBtn").addEventListener("click",()=>{$("settingsModal").classList.add("open");syncSettings();});$("closeSettingsBtn").addEventListener("click",()=>$("settingsModal").classList.remove("open"));$("saveSettingsBtn").addEventListener("click",saveSettings);$("settingsModal").addEventListener("click",e=>{if(e.target.id==="settingsModal")$("settingsModal").classList.remove("open");});document.querySelectorAll(".navBtn").forEach(b=>b.addEventListener("click",()=>switchSection(b.dataset.target)));
loadLocal();loadStatus(false);
